apis/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('quizzes', QuizList.as_view()),
    path('quizzes/<int:pk>', QuizDetail.as_view()),
    path('questions', QuestionList.as_view()),
    path('questions/<int:pk>', QuizDetail.as_view()),
    path('options', OptionList.as_view()),
    path('options/<int:pk>', OptionDetail.as_view()),
]

quiz/urls.py
from django.urls import path
from .views import *
app_name = 'quiz'

urlpatterns = [
    path('take_quiz', QuizList.as_view(), name='take_quiz'),
    path('start_quiz', StartQuiz.as_view(), name='start_quiz')
]

quiz_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from quiz.views import HomeView

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login',),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('admin/', admin.site.urls),
    path('home/', HomeView.as_view(template_name='home.html'), name='home'),
    path('quiz/', include('quiz.urls', namespace='quiz')),

    path('apis/v1/', include('apis.urls')),

]

apis/models.py
from django.db import models

# Create your models here.

quiz/models.py
from django.db import models
from user.models import User


class Quiz(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'quiz'

    def __str__(self):
        return self.name


class Options(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'options'

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.CharField(max_length=200)
    options = models.ManyToManyField(Options, related_name="options", blank=True)
    answer = models.ForeignKey(Options, on_delete=models.DO_NOTHING)
    score = models.IntegerField(default=1)
    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'question'

    def __str__(self):
        return self.question


class UserQuiz(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    total_score = models.IntegerField(default=0)
    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'user_quiz'


class UserQuizDetails(models.Model):
    user_quiz = models.ForeignKey(UserQuiz, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user_answer = models.ForeignKey(Options, on_delete=models.CASCADE, related_name='user_answer')
    correct_answer = models.ForeignKey(Options, on_delete=models.CASCADE, related_name='correct_answer')

    class Meta:
        db_table = 'user_quiz_details'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime, timedelta
import jwt
from django.conf import settings


class User(AbstractUser):
    mobile = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=100)

    class Meta:
        db_table = 'user'

    @property
    def token(self):
        return self._generate_token()

    def _generate_token(self):
        dt = datetime.now() + timedelta(minutes=120)
        token = jwt.encode({'id':self.pk, 'exp': dt}, settings.SECRET_KEY).decode('utf8')

        return token

apis/views.py
from django.shortcuts import render


from rest_framework import generics

from quiz.models import *
from .serializers import *


class QuizList(generics.ListCreateAPIView):
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer


class QuizDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer


class QuestionList(generics.ListCreateAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer


class QuestionDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer


class OptionList(generics.ListCreateAPIView):
    queryset = Options.objects.all()
    serializer_class = QuestionSerializer


class OptionDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Options.objects.all()
    serializer_class = QuestionSerializer

quiz/views.py
from django.shortcuts import render
from django.views import generic
from quiz_project import config
# Create your views here.
from . models import *


class HomeView(generic.ListView):
    def get(self, *args, **kwargs):
        context = {"menus": config.menus}
        return render(self.request, 'home.html', context)


class QuizList(generic.ListView):

    def get(self, *args, **kwargs):
        context = {"menus": config.menus}
        quizes = Quiz.objects.all()
        context['quizes'] = quizes
        return render(self.request, 'quiz_list.html', context)


class StartQuiz(generic.ListView):
    def get(self, request, *args, **kwargs):
        quiz_id = request.GET.get("id", None)
        context = {"menus": config.menus}
        quiz = Quiz.objects.get(pk=quiz_id)
        questions = Question.objects.select_related('option_a').filter(quiz_id=quiz_id).values()
        context['quiz'] = quiz
        context['questions'] = questions
        return render(self.request, 'start_quiz.html', context)

user/views.py
from django.shortcuts import render

# Create your views here.

quiz/templates/home.html
{% extends 'base.html' %}

{% block title %}Home {% endblock %}

{% block content %}
  <ul >
    <li> <a href="{% url 'quiz:take_quiz' %}">Take a new quiz </a></li>
  </ul>
{% endblock %}

quiz/templates/quiz_list.html
{% extends 'base.html' %}

{% block title %}Take a Quiz {% endblock %}

{% block content %}
  <ul >
      {% for quiz in quizes %}

         <li><a href="{% url 'quiz:start_quiz' %}?id={{quiz.id}}">{{quiz.name}}</a></li>
        {% endfor %}
  </ul>
{% endblock %}

quiz/templates/start_quiz.html
{% extends 'base.html' %}

{% block title %} Start Quiz {% endblock %}

{% block content %}
    <h3> {{quiz.name}} </h3>

  <ul >
      {% for question in questions %}
         <li>{{question.question}}</li>
              <ul >
                    <li>{{question.option_a}}</li>
                    <li>{{question.option_b}}</li>
                    <li>{{question.option_c}}</li>
                    <li>{{question.option_d}}</li>
              </ul>
      {% endfor %}
  </ul>

{% endblock %}

user/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  {{static}}
     {% block title %}
    {% endblock %}
</head>
<body>

  <!-- main page content here -->
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <!-- Main content -->
      <section class="content">

        {% block content %}


        {% endblock %}
      </section>
      <!-- /.content -->
    </div>

</body>
</html>

user/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}